description: "Evaluation for Social Safety Net Chatbot (letter-only accuracy + rationale & citations)"

defaultTest:
  vars:
    uniqueSessionId: file://configs/generateUniqueId.js

providers: 
  - file://configs/nava-provider.yaml

prompts:
  - file://prompts/mcq-letter-only.txt

tests:
  - file://datasets/tests.csv
    
evaluateOptions:
  cache: true
  maxConcurrency: 4
  showProgressBar: true

outputPath: "results/latest_result.csv"