description: "Evaluation for Social Safety Net Chatbot (letter-only accuracy + rationale & citations)"

providers:
  - file://configs/nava-provider.yaml

prompts:
  - id: file://prompts/mcq-letter-only.txt
    label: mcq_letter_only

defaultTest:
  vars:
    uniqueSessionId: file://scripts/generateUniqueId.js

tests: file://tests/dataset.csv

evaluateOptions:
  cache: true
  maxConcurrency: 4
  showProgressBar: true

outputPath: "results/latest_result.csv"