description: "Evaluation for Social Safety Net Chatbot (letter-only accuracy + rationale & citations)"

defaultTest:
  vars:
    uniqueSessionId: file://configs/generateUniqueId.js

providers: 
  - file://configs/nava-provider.yaml

tests: file://datasets/tests.csv

evaluateOptions:
  delay: 5
  cache: true
  maxConcurrency: 4
  showProgressBar: true

outputPath: "results/latest_result.csv"