id: https://decision-support-tool-dev.navateam.com/api/query
label: "nava"
config:
  method: POST
  headers:
    Content-Type: application/json
  body:
      chat_history: []
      session_id: "{{uniqueSessionId}}"
      new_session: true
      message: "{{prompt}}"
      user_id: "promptfoo-evaluator"
  transformResponse: "json ? json.response_text : ''"